Remove device role if role not sent
MeshAddicts/meshinfo pull request #75
Opened 2024-08-28 15:23 UTC by afairclo

[mqtt.py](https://github.com/MeshAddicts/meshinfo/blob/43ae523acd59c1c1042d4ed45633c8e4b3e81dcc/mqtt.py#L406) is updating node role info when a role is included with the nodeinfo message, but it appears nodes that are set to Client don't send  "role: 0" in their nodeinfo message.

If device is configured for any other role and is ingested by Meshinfo, and later configured for Client, Meshinfo is not removing the previously set role.

2024-08-30 19:53 UTC, kevinelliott approved these changes
Thanks for the contribution! This looks good.

2024-09-02 16:19 UTC, afairclo reviewed
Missing colon on else statement

2024-09-02 17:15 UTC, afairclo reviewed
Fix zIndex placement

2024-09-03 20:09 UTC, kevinelliott requested changes
Just need to fix the tabs on the indexes.

2024-09-03 20:09 UTC, kevinelliott commented on templates/static/map.html.j2
> +	    zIndex: 0
Fix: tab is wrong for these. Can you adjust?

2024-09-04 17:58 UTC, afairclo reviewed
Adjusted

2024-09-04 19:52 UTC, afairclo reviewed
Indentation adjustments

2024-09-05 18:37 UTC, kevinelliott commented
Looks great! Thanks @afairclo ... merging.

2024-09-05 18:37 UTC, merged